services:
  cockroachdb:
    image: cockroachdb/cockroach:v25.2.8
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data: